name: AMR LookApp (Manual)

on:
  workflow_dispatch:  
  # Позволяет запускать вручную из веб-интерфейса

env:
  tg_channel_id: ${{ secrets.TG_CHANNEL_ID }}
  tg_token: ${{ secrets.TG_TOKEN }}
  #
  #

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f 'Python Scripts/requirements.txt' ]; then pip install -r 'Python Scripts/requirements.txt'; fi
      - name: Execute py script
        run: python 'Python Scripts/AMR_LookApp_github.py'
      - name: Commit files
        run: |
          git config --local user.email "mushroomoff@mail.ru"
          git config --local user.name "MushroomOFF"
          git add -A
          git commit -a -m "AMR LookApp manual run"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main