name: AMR New Releases

on:
  schedule:
    - cron: '9 5 * * 5' # Every Friday at 5:09 UTC (+/- 15 min). 5:09 UTC is 8:09 in Moscow.

env:
  tg_channel_id: ${{ secrets.TG_CHANNEL_ID }}
  tg_token: ${{ secrets.TG_TOKEN }}
  ym_token: ${{ secrets.YM_TOKEN }}
  zv_token: ${{ secrets.ZV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f 'Python Scripts/requirements.txt' ]; then pip install -r 'Python Scripts/requirements.txt'; fi

      - name: Execute py script
        run: python 'Python Scripts/AMR_NewReleases_github.py'

      - name: Commit files
        run: |
          git config --local user.email "mushroomoff@mail.ru"
          git config --local user.name "MushroomOFF"
          git add -A
          git commit -a -m "AMR New Releases autoupdate"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
