name: Test run

on:
  workflow_dispatch:  
  # Позволяет запускать вручную из веб-интерфейса

# env:
#   tg_channel_id: ${{ secrets.TG_CHANNEL_ID }}
#   tg_token: ${{ secrets.TG_TOKEN }}
#   ym_token: ${{ secrets.YM_TOKEN }}
#   zv_token: ${{ secrets.ZV_TOKEN }}

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v5 (test)
        uses: actions/checkout@v5
      - name: Set up v6 (test) Python 3.14.0 (test)
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.0"
      - name: Install dependencies (test)
        run: |
          python -m pip install --upgrade pip
          if [ -f 'Python Scripts/requirements_fresh.txt' ]; then pip install -r 'Python Scripts/requirements_fresh.txt'; fi
      - name: Execute py script
        run: python 'Python Scripts/AMR_Test_run.py'