name: AMR Yandex.Music & Zvuk Lookup

on:
  schedule:
    - cron: '9 6 * * *' # At 06:09 UTC (+/- 15 min) on every day-of-week from Sunday through Thursday and Saturday. 6:09 UTC is 9:09 in Moscow.

env:
  tg_channel_id: ${{ secrets.TG_CHANNEL_ID }}
  tg_token: ${{ secrets.TG_TOKEN }}
  ym_token: ${{ secrets.YM_TOKEN }}
  zv_token: ${{ secrets.ZV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f 'Python Scripts/requirements.txt' ]; then pip install -r 'Python Scripts/requirements.txt'; fi
    - name: execute py script
      run: python 'Python Scripts/AMR_ZVYM_github.py'
    - name: commit files
      run: |
        git config --local user.email "mushroomoff@mail.ru"
        git config --local user.name "MushroomOFF"
        git add -A
        git commit -a -m "weekly AMR Yandex.Music & Zvuk autolookup"
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
